# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0fb79ff06716c490befee9e0faa4372"
name = "wna"
handle = "wna-1"
application_url = "https://flashers-nc-salvation-machine.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testbase2brand.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://flashers-nc-salvation-machine.trycloudflare.com/auth/callback",
  "https://flashers-nc-salvation-machine.trycloudflare.com/auth/shopify/callback",
  "https://flashers-nc-salvation-machine.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
