# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f230c54da1d2c72bf51845dc86f2657"
name = "S-S-wna"
handle = "s-s-wna"
application_url = "https://dec-accommodations-window-number.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-f077c9e4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [
  "https://dec-accommodations-window-number.trycloudflare.com/auth/callback",
  "https://dec-accommodations-window-number.trycloudflare.com/auth/shopify/callback",
  "https://dec-accommodations-window-number.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
