# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "765b11ac4e52a762b5e5956b22ca5c3b"
name = "X-staging-wna"
handle = "x-staging-wna"
application_url = "https://injection-resistant-ordered-verse.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststorewna.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://injection-resistant-ordered-verse.trycloudflare.com/auth/callback",
  "https://injection-resistant-ordered-verse.trycloudflare.com/auth/shopify/callback",
  "https://injection-resistant-ordered-verse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
