# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "68c0496da36fc88a48113e8cca008191"
name = "ai"
handle = "ai-20"
application_url = "https://yields-ids-personality-millions.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aditya-ai.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://yields-ids-personality-millions.trycloudflare.com/auth/callback",
  "https://yields-ids-personality-millions.trycloudflare.com/auth/shopify/callback",
  "https://yields-ids-personality-millions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
