# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "340ba2039f46f00f6038e7fc31013e11"
name = "testapp"
handle = "testapp-3678"
application_url = "https://participant-paperback-inspiration-sim.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "teststorewna.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products"

[auth]
redirect_urls = [
  "https://participant-paperback-inspiration-sim.trycloudflare.com/auth/callback",
  "https://participant-paperback-inspiration-sim.trycloudflare.com/auth/shopify/callback",
  "https://participant-paperback-inspiration-sim.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
