# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "239dcf8af34d2c5a6f9093c65a92bbf9"
name = "wearnowAI"
handle = "wearnowai-1"
application_url = "https://wearnow-shopify-7c945fcdc96d.herokuapp.com/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "teststorewna.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [
  "https://wearnow-shopify-7c945fcdc96d.herokuapp.com/auth/callback",
  "https://wearnow-shopify-7c945fcdc96d.herokuapp.com/auth/shopify/callback",
  "https://wearnow-shopify-7c945fcdc96d.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

[app_preferences]
url = "https://wearnow-shopify-7c945fcdc96d.herokuapp.com/"
