# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "57637fccbd6eb2a7d7f9be2c5d06e77d"
name = "wna"
handle = "wna"
application_url = "https://harry-joy-personality-trunk.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aditya-ai.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://harry-joy-personality-trunk.trycloudflare.com/auth/callback",
  "https://harry-joy-personality-trunk.trycloudflare.com/auth/shopify/callback",
  "https://harry-joy-personality-trunk.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
