# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "bfdb6cc77aeff152d3b1f0187bafbc29"
name = "new-ai-app"
handle = "new-ai-app"
application_url = "https://sweet-sessions-phillips-statistics.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aditya-ai.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sweet-sessions-phillips-statistics.trycloudflare.com/auth/callback",
  "https://sweet-sessions-phillips-statistics.trycloudflare.com/auth/shopify/callback",
  "https://sweet-sessions-phillips-statistics.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
